---
iface_list:
 - { iface: "Serial1/0", ip: "172.22.6.1", mask: "255.255.255.248", desc: "To rtr2", duplex: "full" }
 - { iface: "Serial1/2", ip: "172.22.6.9", mask: "255.255.255.248", desc: "To rtr3", duplex: "full" }
 - { iface: "Loopback0", ip: "10.6.1.1", mask: "255.255.255.0", desc: "Locale", duplex: "full" }
